import { Button, CheckBox, ListView, LineEdit, HorizontalBox, VerticalBox } from "std-widgets.slint";

export struct Task := {
    text: string,
    is_completed: bool,
}

export AppWindow := Window {
    preferred-height: 300px;
    preferred-width: 300px;
    title: "Redo";
    default-font-size: 16px;
    callback add-task(string);
    callback remove-completed();
    property <[Task]> tasks: [];

    VerticalBox {
        HorizontalBox {
            input := LineEdit {
                height: 30px;
                placeholder-text: "Add a new task...";
                accepted(text) => {
                    add-task(text);
                    self.text = "";
                }
            }
            add-btn := Button {
                height: 30px;
                width: 50px;
                font-size: 20px;
                text: "+";
                enabled: input.text != "";
                clicked => { 
                    add-task(input.text);
                    input.text = "";
                }
            }
        }
        task-list := ListView {
            for task in tasks: HorizontalLayout {
                CheckBox {
                    text: task.text;
                    checked: task.is_completed;
                    toggled => {
                        task.is_completed = checked;
                    }
                }
            }
        }
        HorizontalBox {
            alignment: center;
            remove-completed-btn := Button {
                height: 30px;
                font-size: 14px;
                text: "Remove Completed Tasks";
                enabled: tasks.length > 0;
                clicked => { remove-completed(); }
            }
        }
    }
}
